version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html

  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: agenda
      MYSQL_USER: alejandro
      MYSQL_PASSWORD: 123456
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"  # Puerto de MariaDB expuesto para conectividad externa
